# Generated by Django 3.2.8 on 2021-11-03 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(choices=[('Alin', 'Aljabar Linear'), ('MPPI', 'Metodologi Penelitian dan Penulisan Ilmiah'), ('PBP', 'Pemrograman Berbasis Platform'), ('SOSI', 'Sistem Operasi untuk Sistem Informasi'), ('SDA', 'Struktur Data & Algoritma')], max_length=200)),
                ('judul', models.CharField(max_length=80)),
                ('tanggal', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('waktu', models.TimeField(default='23:55')),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
