# Generated by Django 3.2.8 on 2021-10-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='due_date',
            new_name='tanggal',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='nama',
        ),
        migrations.AddField(
            model_name='agenda',
            name='judul',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='matkul',
            field=models.CharField(choices=[('Alin', 'Aljabar Linear'), ('MPPI', 'Metodologi Penelitian dan Penulisan Ilmiah'), ('PBP', 'Pemrograman Berbasis Platform'), ('SOSI', 'Sistem Operasi untuk Sistem Informasi'), ('SDA', 'Struktur Data & Algoritma')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='waktu',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
    ]
