# Generated by Django 3.2.8 on 2021-10-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20211026_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
