# Generated by Django 3.2.7 on 2021-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_a_mentor', '0003_auto_20211230_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
