# Generated by Django 3.2.7 on 2021-11-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penulis', models.CharField(max_length=150)),
                ('Matkul', models.CharField(max_length=150)),
                ('Topik', models.CharField(max_length=150)),
                ('Keterangan', models.TextField()),
                ('Link', models.URLField()),
            ],
        ),
    ]
