# Generated by Django 3.2.8 on 2021-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=15)),
                ('info', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
