# Generated by Django 3.2.7 on 2021-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Link',
            field=models.URLField(),
        ),
    ]
