# Generated by Django 3.2.8 on 2021-10-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Creator',
            field=models.CharField(max_length=50),
        ),
    ]
