# Generated by Django 3.2.7 on 2021-12-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalBelajarBareng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prioritas', models.TextField(choices=[('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], max_length=15)),
                ('Matkul', models.TextField(choices=[('Alin', 'Alin'), ('MPPI', 'MPPI'), ('PBP', 'PBP'), ('SOSI', 'SOSI'), ('SDA', 'SDA')], max_length=150)),
                ('Waktu', models.CharField(max_length=150)),
                ('Topik', models.CharField(max_length=150)),
                ('Informasi', models.TextField()),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
    ]
