# Generated by Django 3.2.9 on 2021-11-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal_belajar_bareng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalbelajarbareng',
            name='user',
        ),
    ]
