# Generated by Django 3.2.8 on 2021-11-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('Alin', 'Aljabar Linear'), ('MPPI', 'Metodologi Penelitian dan Penulisan Ilmiah'), ('PBP', 'Pemrograman Berbasis Platform'), ('SOSI', 'Sistem Operasi untuk Sistem Informasi'), ('SDA', 'Struktur Data & Algoritma')], max_length=200)),
                ('kelas', models.CharField(max_length=1)),
                ('SKS', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat')], max_length=10)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_kuliah.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomor_telepon', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_kuliah.matakuliah')),
            ],
        ),
    ]
