# Generated by Django 3.2.7 on 2021-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_kuliah', '0002_matakuliah_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='SKS',
            field=models.IntegerField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Dosen',
        ),
    ]
